packages:
  base: !include packages/base.yml
  device_base: !include boards/m5stack-nanoc6-i2c.yml

dashboard_import:
  package_import_url: github://rnewman/esphome-m5-btproxy/esphome-m5-btproxy-m5stack-nanoc6-i2c.yml
